// Comprehensive dataset of 105+ inspirational quotes across multiple categories and moods
const seedQuotes = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "Motivation", tags: ["success", "work", "passion"], mood: "motivated" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", category: "Technology", tags: ["innovation", "leadership", "tech"], mood: "ambitious" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "Motivation", tags: ["dreams", "future", "belief"], mood: "motivated" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", category: "Wisdom", tags: ["strength", "resilience", "hope"], mood: "calm" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "Success", tags: ["courage", "perseverance", "failure"], mood: "confident" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama", category: "Happiness", tags: ["happiness", "action", "self"], mood: "happy" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein", category: "Wisdom", tags: ["opportunity", "challenge", "growth"], mood: "motivated" },
  { text: "A friend is someone who knows all about you and still loves you.", author: "Elbert Hubbard", category: "Friendship", tags: ["friendship", "love", "acceptance"], mood: "loved" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", category: "Life", tags: ["action", "time", "growth"], mood: "motivated" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt", category: "Success", tags: ["doubt", "future", "potential"], mood: "confident" },
  { text: "Love is not about how many days, months, or years you have been together. It is about how much you love each other every single day.", author: "Unknown", category: "Love", tags: ["love", "commitment", "daily"], mood: "loved" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", category: "Study", tags: ["education", "change", "power"], mood: "focused" },
  { text: "Creativity is intelligence having fun.", author: "Albert Einstein", category: "Creativity", tags: ["creativity", "intelligence", "fun"], mood: "happy" },
  { text: "A leader is one who knows the way, goes the way, and shows the way.", author: "John C. Maxwell", category: "Leadership", tags: ["leadership", "guidance", "example"], mood: "confident" },
  { text: "Technology is best when it brings people together.", author: "Matt Mullenweg", category: "Technology", tags: ["technology", "connection", "people"], mood: "happy" },
  { text: "The mind is everything. What you think you become.", author: "Buddha", category: "Wisdom", tags: ["mind", "thoughts", "becoming"], mood: "calm" },
  { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats", category: "Motivation", tags: ["action", "initiative", "determination"], mood: "ambitious" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "Life", tags: ["resilience", "perseverance", "glory"], mood: "motivated" },
  { text: "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'", author: "C.S. Lewis", category: "Friendship", tags: ["friendship", "connection", "understanding"], mood: "happy" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau", category: "Success", tags: ["success", "work", "focus"], mood: "focused" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "Happiness", tags: ["purpose", "happiness", "life"], mood: "happy" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon", category: "Life", tags: ["life", "plans", "present"], mood: "calm" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "Motivation", tags: ["journey", "beginning", "possibility"], mood: "ambitious" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde", category: "Wisdom", tags: ["authenticity", "self", "identity"], mood: "confident" },
  { text: "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.", author: "Helen Keller", category: "Love", tags: ["beauty", "feeling", "heart"], mood: "loved" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", category: "Study", tags: ["learning", "life", "wisdom"], mood: "focused" },
  { text: "Creativity takes courage.", author: "Henri Matisse", category: "Creativity", tags: ["creativity", "courage", "art"], mood: "confident" },
  { text: "Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.", author: "Jack Welch", category: "Leadership", tags: ["leadership", "growth", "success"], mood: "ambitious" },
  { text: "Any sufficiently advanced technology is indistinguishable from magic.", author: "Arthur C. Clarke", category: "Technology", tags: ["technology", "magic", "future"], mood: "ambitious" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "Motivation", tags: ["belief", "confidence", "progress"], mood: "confident" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Success", tags: ["action", "start", "progress"], mood: "motivated" },
  { text: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman", category: "Happiness", tags: ["positivity", "optimism", "sunshine"], mood: "happy" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar", category: "Study", tags: ["beginning", "greatness", "learning"], mood: "motivated" },
  { text: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein", category: "Creativity", tags: ["intelligence", "imagination", "creativity"], mood: "calm" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", category: "Wisdom", tags: ["inner strength", "potential", "self"], mood: "confident" },

  // Additional 70+ curated quotes to reach 105+ total
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "Motivation", tags: ["perseverance", "possibility", "hope"], mood: "motivated" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs", category: "Life", tags: ["time", "authenticity", "focus"], mood: "confident" },
  { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein", category: "Happiness", tags: ["goals", "happiness", "purpose"], mood: "focused" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth", category: "Success", tags: ["fearless", "action", "courage"], mood: "confident" },
  { text: "Money and success don't change people; they merely amplify what is already there.", author: "Will Smith", category: "Wisdom", tags: ["character", "success", "wealth"], mood: "calm" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", category: "Wisdom", tags: ["growth", "resilience", "healing"], mood: "calm" },
  { text: "If you can dream it, you can do it.", author: "Walt Disney", category: "Creativity", tags: ["dreams", "creativity", "belief"], mood: "happy" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", category: "Motivation", tags: ["action", "resourcefulness", "now"], mood: "motivated" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", category: "Motivation", tags: ["courage", "fear", "growth"], mood: "ambitious" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis", category: "Wisdom", tags: ["destiny", "hardship", "strength"], mood: "calm" },
  { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson", category: "Motivation", tags: ["belief", "confidence", "overcoming"], mood: "confident" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "Success", tags: ["action", "execution", "start"], mood: "motivated" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers", category: "Life", tags: ["present", "focus", "letting go"], mood: "calm" },
  { text: "You learn more from failure than from success. Don't let it stop you. Failure builds character.", author: "Unknown", category: "Study", tags: ["failure", "learning", "character"], mood: "focused" },
  { text: "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you.", author: "Steve Jobs", category: "Leadership", tags: ["vision", "passion", "drive"], mood: "ambitious" },
  { text: "People who are crazy enough to think they can change the world are the ones who do.", author: "Rob Siltanen", category: "Technology", tags: ["change", "vision", "impact"], mood: "ambitious" },
  { text: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino", category: "Success", tags: ["determination", "resilience", "grit"], mood: "confident" },
  { text: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang von Goethe", category: "Study", tags: ["action", "application", "discipline"], mood: "focused" },
  { text: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link", category: "Motivation", tags: ["action", "fear", "overcoming"], mood: "motivated" },
  { text: "Whether you think you can or think you can't, you're right.", author: "Henry Ford", category: "Wisdom", tags: ["mindset", "belief", "attitude"], mood: "confident" },
  { text: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller", category: "Life", tags: ["adventure", "risk", "living"], mood: "ambitious" },
  { text: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb", category: "Leadership", tags: ["confidence", "trust", "leadership"], mood: "confident" },
  { text: "The only limit to our height is how high we choose to jump.", author: "Unknown", category: "Motivation", tags: ["potential", "choice", "ambition"], mood: "ambitious" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde", category: "Life", tags: ["living", "presence", "awareness"], mood: "calm" },
  { text: "Blessed are those who can give without remembering and take without forgetting.", author: "Elizabeth Asquith Bibesco", category: "Wisdom", tags: ["generosity", "gratitude", "kindness"], mood: "calm" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt", category: "Motivation", tags: ["courage", "growth", "challenge"], mood: "ambitious" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar", category: "Success", tags: ["growth", "goals", "becoming"], mood: "focused" },
  { text: "If you love life, don't waste time, for time is what life is made up of.", author: "Bruce Lee", category: "Life", tags: ["time", "discipline", "life"], mood: "motivated" },
  { text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare", category: "Love", tags: ["trust", "love", "integrity"], mood: "loved" },
  { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein", category: "Technology", tags: ["adaptability", "intelligence", "change"], mood: "focused" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent Van Gogh", category: "Creativity", tags: ["small steps", "consistency", "mastery"], mood: "calm" },
  { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale", category: "Wisdom", tags: ["mindset", "thoughts", "change"], mood: "motivated" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", category: "Leadership", tags: ["leadership", "change", "example"], mood: "confident" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs", category: "Technology", tags: ["curiosity", "learning", "innovation"], mood: "ambitious" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot", category: "Motivation", tags: ["possibility", "transformation", "hope"], mood: "motivated" },
  { text: "A unexamined life is not worth living.", author: "Socrates", category: "Wisdom", tags: ["reflection", "self-awareness", "philosophy"], mood: "calm" },
  { text: "There is no charm equal to tenderness of heart.", author: "Jane Austen", category: "Love", tags: ["tenderness", "heart", "kindness"], mood: "loved" },
  { text: "The function of leadership is to produce more leaders, not more followers.", author: "Ralph Nader", category: "Leadership", tags: ["leadership", "empowerment", "coaching"], mood: "confident" },
  { text: "Computers are incredibly fast, accurate, and stupid. Human beings are incredibly slow, inaccurate, and brilliant. Together they are powerful beyond imagination.", author: "Albert Einstein", category: "Technology", tags: ["computers", "humanity", "collaboration"], mood: "ambitious" },
  { text: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein", category: "Success", tags: ["value", "character", "integrity"], mood: "calm" },
  { text: "The root of suffering is attachment.", author: "Buddha", category: "Wisdom", tags: ["peace", "attachment", "mindfulness"], mood: "calm" },
  { text: "Study the past if you would define the future.", author: "Confucius", category: "Study", tags: ["history", "learning", "future"], mood: "focused" },
  { text: "Light tomorrow with today!", author: "Elizabeth Barrett Browning", category: "Happiness", tags: ["positivity", "today", "hope"], mood: "happy" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi", category: "Love", tags: ["love", "life", "vitality"], mood: "loved" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", category: "Leadership", tags: ["trailblazer", "pioneer", "courage"], mood: "ambitious" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", category: "Success", tags: ["enthusiasm", "resilience", "perseverance"], mood: "motivated" },
  { text: "The art of art, the glory of expression and the sunshine of the light of letters, is simplicity.", author: "Walt Whitman", category: "Creativity", tags: ["simplicity", "art", "expression"], mood: "calm" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso", category: "Creativity", tags: ["action", "foundation", "success"], mood: "motivated" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin", category: "Study", tags: ["learning", "involvement", "education"], mood: "focused" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci", category: "Creativity", tags: ["simplicity", "design", "elegance"], mood: "calm" },
  { text: "Joy is not in things; it is in us.", author: "Richard Wagner", category: "Happiness", tags: ["joy", "inner peace", "happiness"], mood: "happy" },
  { text: "Peace begins with a smile.", author: "Mother Teresa", category: "Happiness", tags: ["peace", "smile", "kindness"], mood: "happy" },
  { text: "The power of imagination makes us infinite.", author: "John Muir", category: "Creativity", tags: ["imagination", "infinity", "wonder"], mood: "happy" },
  { text: "Mastering others is strength. Mastering yourself is true power.", author: "Lao Tzu", category: "Wisdom", tags: ["self-mastery", "strength", "power"], mood: "confident" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu", category: "Wisdom", tags: ["silence", "peace", "inner strength"], mood: "calm" },
  { text: "To love and be loved is to feel the sun from both sides.", author: "David Viscott", category: "Love", tags: ["love", "reciprocity", "warmth"], mood: "loved" },
  { text: "Real learning comes when the competitive spirit has ceased.", author: "Jiddu Krishnamurti", category: "Study", tags: ["learning", "competition", "growth"], mood: "focused" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan", category: "Motivation", tags: ["dreams", "courage", "risk"], mood: "ambitious" },
  { text: "Fall seven times and stand up eight.", author: "Japanese Proverb", category: "Success", tags: ["resilience", "persistence", "grit"], mood: "motivated" },
  { text: "When you have a dream, you've got to grab it and never let go.", author: "Carol Burnett", category: "Motivation", tags: ["dreams", "tenacity", "focus"], mood: "motivated" },
  { text: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn", category: "Happiness", tags: ["possibility", "optimism", "joy"], mood: "happy" },
  { text: "There is always light, if only we're brave enough to see it. If only we're brave enough to be it.", author: "Amanda Gorman", category: "Leadership", tags: ["light", "bravery", "hope"], mood: "confident" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa", category: "Love", tags: ["love", "kindness", "joy"], mood: "loved" },
  { text: "The science of today is the technology of tomorrow.", author: "Edward Teller", category: "Technology", tags: ["science", "technology", "future"], mood: "ambitious" },
  { text: "The contrast is what makes photography interesting.", author: "Conrad Hall", category: "Creativity", tags: ["contrast", "perspective", "art"], mood: "calm" },
  { text: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.", author: "Brian Herbert", category: "Study", tags: ["learning", "willingness", "choice"], mood: "focused" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem", category: "Motivation", tags: ["doubt", "belief", "courage"], mood: "confident" },
  { text: "Optimization is the enemy of development.", author: "Donald Knuth", category: "Technology", tags: ["programming", "development", "wisdom"], mood: "focused" },
  { text: "First, solve the problem. Then, write the code.", author: "John Johnson", category: "Technology", tags: ["programming", "problem-solving", "code"], mood: "focused" },
  { text: "Make it work, make it right, make it fast.", author: "Kent Beck", category: "Technology", tags: ["software", "craftsmanship", "execution"], mood: "motivated" }
];

export default seedQuotes;
